services:
  # app:
  #   build:
  #     dockerfile: dockerfile.bundle
  #   ports:
  #     - 5173:5173
  #     - 8000:8000
    # command: ["pnpm", "--prefix", "/opt/app/client", "vite" ,"&" ,"gunicorn" , "--bind", "0.0.0.0:8000", "inventory.wsgi"]
  client:
    build:
      dockerfile: dockerfile.client
    ports:
      - 5173:5173
    # command: ["pnpm", "vite", "--host", "--port", "5173"]
  # server:
  #   build:
  #     dockerfile: dockerfile.server
  #   ports:
  #     - 8000:8000
  #   command: ["gunicorn", "--bind", "0.0.0.0:8000", "inventory.wsgi"]
