FROM python:3.13-slim

WORKDIR /opt/app

COPY server .


RUN apt update
RUN apt install -y \
    libpq-dev \
    gcc
RUN pip install -r requirements.txt
RUN python manage.py collectstatic --no-input

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "inventory.wsgi"]
