# Generated by Django 5.2.1 on 2025-06-02 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('PVT', 'PVT'), ('PV2', 'PV2'), ('PFC', 'PFC'), ('SPC', 'SPC'), ('SGT', 'SGT'), ('SSG', 'SSG'), ('SFC', 'SFC'), ('MSG', 'MSG'), ('1SG', '1SG'), ('SMG', 'SMG'), ('CSM', 'CSM'), ('2LT', '2LT'), ('1LT', '1LT'), ('CPT', 'CPT'), ('MAJ', 'MAJ'), ('LTC', 'LTC'), ('COL', 'COL')], max_length=4)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=1)),
                ('action', models.BooleanField(choices=[('BORROW', True), ('RETURN', False)], default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='chest.chest')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='chest.item')),
            ],
        ),
    ]
