# Generated by Django 5.2.1 on 2025-06-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrecord',
            name='action',
            field=models.BooleanField(choices=[(True, 'BORROW'), (False, 'RETURN')], default=True),
        ),
        migrations.AlterField(
            model_name='accountrecord',
            name='rank',
            field=models.CharField(choices=[('PVT', 'PVT'), ('PV2', 'PV2'), ('PFC', 'PFC'), ('SPC', 'SPC'), ('SGT', 'SGT'), ('SSG', 'SSG'), ('SFC', 'SFC'), ('MSG', 'MSG'), ('1SG', '1SG'), ('SMG', 'SMG'), ('CSM', 'CSM'), ('2LT', '2LT'), ('1LT', '1LT'), ('CPT', 'CPT'), ('MAJ', 'MAJ'), ('LTC', 'LTC'), ('COL', 'COL'), ('NONE', 'NONE')], max_length=4),
        ),
    ]
