# Generated by Django 5.2.1 on 2025-06-04 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plt', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('nsn', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('case_number', models.IntegerField(default=1)),
                ('case_total', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('serial', 'case_number')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('name_ext', models.CharField(blank=True, max_length=100, null=True)),
                ('nsn', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_total', models.IntegerField(default=1)),
                ('qty_real', models.IntegerField(default=1)),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='chest.chest')),
            ],
        ),
    ]
