# Generated by Django 5.2.1 on 2025-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest',
            name='drive_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
