# Generated by Django 5.2.1 on 2025-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chest', '0002_chest_drive_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
