# Generated by Django 5.2.1 on 2025-06-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountrecord',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='accountrecord',
            name='rank',
        ),
    ]
