# Generated by Django 5.2.1 on 2025-06-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0003_rename_user_id_accountrecord_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountrecord',
            old_name='qty',
            new_name='original_qty',
        ),
        migrations.AddField(
            model_name='accountrecord',
            name='current_qty',
            field=models.IntegerField(default=1),
        ),
    ]
