# Generated by Django 5.2.1 on 2025-06-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0004_rename_qty_accountrecord_original_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrecord',
            name='transaction_qty',
            field=models.IntegerField(default=1),
        ),
    ]
