# Generated by Django 5.2.1 on 2025-06-06 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0005_accountrecord_transaction_qty'),
        ('chest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItemCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_qty', models.IntegerField(default=1)),
                ('current_qty', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_custody', to='chest.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_custody', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
