# Generated by Django 5.2.1 on 2025-06-06 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0006_useritemcustody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrecord',
            name='current_qty',
        ),
        migrations.RemoveField(
            model_name='useritemcustody',
            name='original_qty',
        ),
        migrations.AddField(
            model_name='accountrecord',
            name='user_item_custody',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accountability.useritemcustody'),
        ),
    ]
