# Generated by Django 5.2.1 on 2025-06-08 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0008_alter_accountrecord_user_item_custody'),
        ('chest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChestCustody',
            fields=[
                ('useritemcustody_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accountability.useritemcustody')),
                ('chest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_custody', to='chest.chest')),
            ],
            bases=('accountability.useritemcustody',),
        ),
    ]
