# Generated by Django 5.2.1 on 2025-06-11 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0009_userchestcustody'),
        ('chest', '0002_chest_drive_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChestInventoryPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_pdf', to='chest.chest')),
            ],
        ),
    ]
