name: Ping URL

on:
  schedule:
    - cron: '*/5 11-23 * * *'  # Every 10 minutes from 6 AM to 5:59 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping two URLs with retry
        run: |
          curl --location 'https://two72-inventory.onrender.com/chest/search?term=divider'
          curl --location 'https://toolhub272.onrender.com/'
