name: Ping URL

on:
  schedule:
    - cron: '*/10 6-17 * * *'
  workflow_dispatch:  # 👈 Enables manual runs

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping two URLs
        run: |
          curl -fsS https://two72-inventory.onrender.com/chest/search?term=divider
          curl -fsS https://toolhub272.onrender.com/
